import numpy as np
import matplotlib.pyplot as plt
import sys

# Import the continued-fraction module, which is used to evaluate
# resolvents and spectral densities from the loaded data.
import mrock.continued_fraction as cf

# Import data-loading utilities and parameter helper functions.
# This includes DataLoader and continuum_params.
from mrock.get_data import *

# Create a global DataLoader instance.
# By default, this will look for data in the package's default data directory
# or in the directory specified by the MROCK_DATA_DIR environment variable.
data_loader = DataLoader()


def load_data(name):
    """Returns the data for the continuum test case with the given name.

    Available names
    ---------------
    no_coulomb
        No Coulomb interaction.

    normal_screening
        Coulomb interaction with normal screening.

    weak_screening
        Coulomb interaction with very weak screening.

    strong_attraction
        No Coulomb interaction but stronger attractive coupling.
    """

    # Each branch below loads one specific simulation data set.
    #
    # The data are stored under:
    #
    #     data / continuum / test / parameter-folders / resolvents.json.gz
    #
    # The exact parameter-folder path is generated by continuum_params(...),
    # which converts the physical and numerical parameters into a dictionary
    # of path components such as:
    #
    #     N_k=4000 / T=0.0 / coulomb_scaling=0.0 / ...
    #
    # The DataLoader then loads the compressed JSON file as a pandas object.

    if name == "no_coulomb":
        # Load a reference calculation without Coulomb interaction.
        return data_loader.load_panda(
            model="continuum",
            subdir="test",
            file="resolvents.json.gz",
            **continuum_params(
                N_k=4000,
                T=0,
                coulomb_scaling=0,
                screening=0,
                k_F=4.25,
                g=0.5,
                omega_D=10
            )
        )

    elif name == "normal_screening":
        # Load a calculation with Coulomb interaction and standard screening.
        return data_loader.load_panda(
            model="continuum",
            subdir="test",
            file="resolvents.json.gz",
            **continuum_params(
                N_k=4000,
                T=0,
                coulomb_scaling=1,
                screening=1,
                k_F=4.25,
                g=0.8,
                omega_D=10
            )
        )

    elif name == "weak_screening":
        # Load a calculation with Coulomb interaction but very weak screening.
        # A small screening value makes the Coulomb interaction more long-ranged.
        return data_loader.load_panda(
            model="continuum",
            subdir="test",
            file="resolvents.json.gz",
            **continuum_params(
                N_k=4000,
                T=0,
                coulomb_scaling=1,
                screening=1e-4,
                k_F=4.25,
                g=1,
                omega_D=10
            )
        )

    elif name == "strong_attraction":
        # Load a calculation without Coulomb interaction but with stronger
        # attractive coupling g.
        return data_loader.load_panda(
            model="continuum",
            subdir="test",
            file="resolvents.json.gz",
            **continuum_params(
                N_k=4000,
                T=0,
                coulomb_scaling=0,
                screening=0,
                k_F=4.25,
                g=1.5,
                omega_D=10
            )
        )

    else:
        # If the user passes an unknown test name, stop with a clear error.
        raise ValueError(f"Continuum test: Invalid name given: {name}")


def create_plot(name):
    """Load one continuum test case and plot phase and Higgs spectral densities."""

    # Load the selected data set.
    #
    # pd_data contains metadata, continuum boundaries, and continued-fraction
    # coefficients for different resolvents.
    pd_data = load_data(name)

    # Create a ContinuedFraction object from the loaded data.
    #
    # This object knows how to evaluate the continued fractions stored in
    # pd_data. The parameters ignore_first and ignore_last control how the
    # automatic termination depth is chosen:
    #
    # - ignore_first=30:
    #   skip the first 30 coefficients when searching for the best asymptotic
    #   termination point.
    #
    # - ignore_last=90:
    #   inspect up to the first 90 coefficients for the termination-depth search.
    resolvents = cf.ContinuedFraction(
        pd_data,
        ignore_first=30,
        ignore_last=90
    )

    fig, ax = plt.subplots()
    ax.set_ylim(-0.05, 1.)
    ax.set_xlabel(r"$\omega [\mathrm{meV}]$")
    ax.set_ylabel(r"$\mathcal{A} (\omega) [\mathrm{eV}^{-1}]$")

    # Build the frequency grid on which the spectral densities are evaluated.
    #
    # dtype=complex is used because the continued fraction is evaluated at
    # complex frequencies.
    w_lin = np.linspace(
        -0.005 * pd_data["continuum_boundaries"][1],
        1.1 * pd_data["continuum_boundaries"][1],
        5000,
        dtype=complex
    )

    # Add a small positive imaginary part to the frequency.
    #
    # This broadens sharp spectral features and corresponds to evaluating the
    # retarded response slightly above the real axis:
    #
    #     omega -> omega + i eta
    #
    # with eta = 1e-4.
    w_lin += 1e-4j

    # Plot the phase spectral density.
    #
    # The continued-fraction data set contains a resolvent named "phase_SC".
    # spectral_density(...) evaluates
    #
    #     A(omega) = -1 / pi * Im G(omega)
    #
    # where G is the continued-fraction resolvent.
    #
    # The x-values are multiplied by 1e3 to convert from eV to meV.
    ax.plot(
        1e3 * w_lin.real,
        resolvents.spectral_density(
            w_lin,
            "phase_SC",
            with_terminator=True
        ),
        label="Phase"
    )

    # Plot the amplitude/Higgs spectral density.
    #
    # This is analogous to the phase mode above, but uses the resolvent
    # "amplitude_SC".
    ax.plot(
        1e3 * w_lin.real,
        resolvents.spectral_density(
            w_lin,
            "amplitude_SC",
            with_terminator=True
        ),
        label="Higgs"
    )

    # Shade the continuum region in the plot.
    #
    # mark_continuum reads the continuum boundaries from the ContinuedFraction
    # object and draws a grey vertical span.
    #
    # The factor 1e3 converts the continuum edges from eV to meV, matching the
    # x-axis units.
    resolvents.mark_continuum(ax, 1e3)

    ax.set_xlim(
        1e3 * np.min(w_lin.real),
        1e3 * np.max(w_lin.real)
    )
    ax.set_title(f"Continuum: {name}")
    ax.legend()
    fig.tight_layout()
    fig.savefig(f"test_result_{name}.pdf")


# Command-line interface:
#
# If the script is called with an additional argument, use that argument as
# the name of the test case to plot.
#
# Example:
#
#     python plot_continuum.py no_coulomb
#
# or:
#
#     python plot_continuum.py weak_screening
#
# If no argument is provided, print a short instruction instead.
if len(sys.argv) > 1:
    create_plot(sys.argv[1])
else:
    print("Please provide the name of the test you would like to plot.")